# Generated by Django 4.0 on 2022-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student1', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
