# Generated by Django 4.0 on 2022-01-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student1', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
